### PR TITLE
MinMicroG: Support lineage recovery and dynamic partitions devices

### PR DESCRIPTION
**Pull request by Linux4**
With the previous install script we'd try to mount /system which is in fstab on lineage recovery, but on Q and up recoveries recovery has it's own /system and all the executables are in /system/bin rather than /sbin, resulting in tools like "chcon" missing after mounting /system
Also on dynamic partitions devices /system is not in fstab due to the block device being only created when logical partitions are mapped, support that case as well

Most of the code is taken from
https://gitlab.com/MindTheGapps/vendor_gapps/-/blob/tau/build/meta/com/google/android/update-binary

### CODE REVIEW

**Comment by Linux4** [comment]
@FriendlyNeighborhoodShane Any review on this one?

**Comment by FriendlyNeighborhoodShane** [comment]
Hi, sorry for the radio silence for all this while, I've been busy with IRL stuff.

Thank you for adding this much-needed change. I have not been able to make or test this myself due to not owning an unlockable dynamic partition device, unfortunately (though I did recently get one which will serve these purposes nicely).

This looks good (except for stylistic changes, which I won't bother you with). I just want to ask, because I can't test this myself, which devices have you tested this to be working on?

**Comment by FriendlyNeighborhoodShane** [comment]
I pushed a refactored version: https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/ec41f892f2c4169ac5b376d9b760bac40e3db5e9

Does it look alright? Will trigger CI test builds soon

**Comment by Linux4** [comment]
Hi, thanks for your response
I had initially tested this on gta4xlwifi (dynamic) and beyond1lte (non-dynamic) both using lineage recovery
Your refactored commit looks about right to me, can re-test with your CI builds later if you'd like me to

**Comment by Linux4** [comment]
> I pushed a refactored version: [20f467c](https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/20f467c6b0de8538be283cae5fc8f39fd774fd2a)
> 
> Does it look alright? Will trigger CI test builds soon

Hi, thanks for your response
I had initially tested this on gta4xlwifi (dynamic) and beyond1lte (non-dynamic) both using lineage recovery
Your refactored commit looks about right to me, can re-test with your CI builds later if you'd like me to

**Comment by FriendlyNeighborhoodShane** [comment]
Only if you're okay with that. I'd appreciate the person who wrote the original code verifying it works.

https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.12.31

**Comment by Linux4** [comment]
There's one small mistake here:

https://github.com/FriendlyNeighborhoodShane/MinMicroG/blob/master/src/META-INF/com/google/android/update-binary#L80

it should be ro.boot.dynamic_partitions instead of ro.dynamicpart, works fine on both devices after correcting that.

**Comment by FriendlyNeighborhoodShane** [comment]
> There's one small mistake here:
> 
> https://github.com/FriendlyNeighborhoodShane/MinMicroG/blob/master/src/META-INF/com/google/android/update-binary#L80
> 
> it should be ro.boot.dynamic_partitions instead of ro.boot.dynamicpart, works fine on both devices after correcting that.

Ah shit, I should've been more careful with automatic replacement. Thanks for testing and for the fix!

**Comment by FriendlyNeighborhoodShane** [comment]
fixed: https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/3c7ab5190192e5c1829f08dd0b64fa9c87edcf60

**Pull request merged**
